"""Sample Newton 1.3 elliptic-friction regression tests.

These are meant to be copied or adapted into a Newton checkout and run from
that checkout:

  uv run --extra sim --with pytest pytest -q \
    mjwarp-elliptic-friction-nan/newton_1_3_sample_tests.py

Expected on Newton release-1.3 at v1.3.0rc1 / commit 3389003b:

* test_newton_per_contact_friction_scale_keeps_mjwarp_floor fails because
  release-1.3 floors the mixed geom friction before applying a positive
  per-contact friction scale, but does not floor it again after scaling.
* test_pinned_mjwarp_external_zero_friction_has_finite_quad fails because the
  pinned mujoco_warp 3.8.1 solver still accepts externally written zero
  contact friction and produces an infinite line-search quad entry.
* test_plain_zero_friction_newton_contacts_are_currently_masked passes and
  documents why the simplest zero-friction Newton contact no longer reproduces
  on release-1.3.
"""

import numpy as np
import warp as wp

import newton
from newton._src.sim.contacts import Contacts
from newton.solvers import SolverMuJoCo


MJ_MINMU = 1.0e-5


def _sphere_on_ground_model(*, mu: float, z: float = 0.49):
  builder = newton.ModelBuilder()
  builder.default_shape_cfg.ke = 1.0e4
  builder.default_shape_cfg.kd = 1000.0
  builder.default_shape_cfg.mu = mu
  builder.default_shape_cfg.mu_torsional = mu
  builder.default_shape_cfg.mu_rolling = mu
  builder.add_ground_plane()

  radius = 0.5
  body = builder.add_body(xform=wp.transform(wp.vec3(0.0, 0.0, z), wp.quat_identity()))
  builder.add_shape_sphere(body=body, radius=radius)
  return builder.finalize()


def _step_newton_mujoco(model, contacts, *, collide: bool = True):
  solver = SolverMuJoCo(
    model,
    use_mujoco_contacts=False,
    cone="elliptic",
    solver="newton",
    integrator="euler",
    iterations=25,
    ls_iterations=25,
  )
  state_in = model.state()
  state_out = model.state()
  control = model.control()
  newton.eval_fk(model, model.joint_q, model.joint_qd, state_in)
  state_in.clear_forces()
  if collide:
    model.collide(state_in, contacts)
  solver.step(state_in, state_out, control, contacts, 0.002)
  wp.synchronize()
  return solver


def test_newton_per_contact_friction_scale_keeps_mjwarp_floor():
  """Fails on release-1.3: post-scale slide friction is below MJ_MINMU."""
  model = _sphere_on_ground_model(mu=1.0)

  # Use the same capacities as Newton's collision pipeline, but request the
  # optional per-contact shape-property arrays so rigid_contact_friction exists.
  model.contacts()
  pipeline = model._collision_pipeline
  contacts = Contacts(
    pipeline.rigid_contact_max,
    pipeline.soft_contact_max,
    device=model.device,
    per_contact_shape_properties=True,
  )

  state = model.state()
  newton.eval_fk(model, model.joint_q, model.joint_qd, state)
  model.collide(state, contacts)
  wp.synchronize()
  assert int(contacts.rigid_contact_count.numpy()[0]) > 0

  # This models a positive per-contact friction scale generated by contact
  # reduction. release-1.3 applies it after contact_params() has already floored
  # geom friction, but does not floor the scaled result again.
  contacts.rigid_contact_friction.assign(
    np.full(contacts.rigid_contact_friction.shape, 1.0e-40, dtype=np.float32)
  )

  solver = _step_newton_mujoco(model, contacts, collide=False)
  nacon = int(solver.mjw_data.nacon.numpy()[0])
  friction = solver.mjw_data.contact.friction.numpy()[0, :nacon]

  assert nacon > 0
  assert np.all(friction >= MJ_MINMU), friction.tolist()


def test_pinned_mjwarp_external_zero_friction_has_finite_quad():
  """Fails on Newton release-1.3's pinned mujoco_warp 3.8.1 stack."""
  import mujoco
  import mujoco_warp as mjw
  from mujoco_warp import test_data
  from mujoco_warp._src import solver
  from mujoco_warp._src import types

  xml = """
  <mujoco>
    <option cone="elliptic" solver="Newton" iterations="20" ls_iterations="20" timestep="0.002"/>
    <worldbody>
      <geom type="plane" size="2 2 .1" condim="3" friction="1 0 0"/>
      <body pos="0 0 .095">
        <freejoint/>
        <geom type="sphere" size=".1" mass="1" condim="3" friction="1 0 0"/>
      </body>
    </worldbody>
  </mujoco>
  """
  _, _, m, d = test_data.fixture(
    xml=xml,
    overrides={
      "opt.jacobian": mujoco.mjtJacobian.mjJAC_DENSE,
      "opt.ls_parallel": False,
    },
  )

  mjw.step(m, d)
  d.contact.friction.fill_(types.vec5(0.0, 0.0, 0.0, 0.0, 0.0))

  mjw.make_constraint(m, d)
  ctx = solver.create_solver_context(m, d)
  solver._solve(m, d, ctx)

  nefc = int(d.nefc.numpy()[0])
  quad = ctx.quad.numpy()[0, :nefc]
  assert np.isfinite(quad).all(), quad.tolist()


def test_plain_zero_friction_newton_contacts_are_currently_masked():
  """Passes on release-1.3 because contact_params floors geom friction."""
  model = _sphere_on_ground_model(mu=0.0)
  contacts = model.contacts()
  solver = _step_newton_mujoco(model, contacts)

  nacon = int(solver.mjw_data.nacon.numpy()[0])
  nefc = int(solver.mjw_data.nefc.numpy()[0])
  friction = solver.mjw_data.contact.friction.numpy()[0, :nacon]
  efc_force = solver.mjw_data.efc.force.numpy()[0, :nefc]

  assert nacon > 0
  assert np.all(friction >= MJ_MINMU), friction.tolist()
  assert np.isfinite(solver.mjw_data.qpos.numpy()).all()
  assert np.isfinite(solver.mjw_data.qvel.numpy()).all()
  assert np.isfinite(solver.mjw_data.qacc.numpy()).all()
  assert np.isfinite(efc_force).all()
